spring.application.name=EmployeeSpringBootApp
spring.datasource.url=jdbc:mysql://localhost:3306/EmployeeDB
spring.datasource.username=root
spring.datasource.password=Akshay@16479

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect